### ISSUE TITLE
Issue with stripped_text when replying from Hotmail

### ISSUE THREAD

**Issue by ntls** [mailgun/talon#49] opened 2015-06-23 10:56 UTC
I have found that if I send an email from mailgun to a hotmail account and I want to reply to that, the body looks like this:
```
My reply message...
<div><hr id="stopSpelling">
Subject: Sending a message from Mailgun's API<br>
From: ____@email.com<br>
To: ____@hotmail.com<br>
Date: Thu, 18 Jun 2015 07:45:36 +0000<br>
etc.....
```
The stripped_text now is "My reply message... Subject: Sending a message from Mailgun's API" but it should be "My reply message..."

As to my understanding when you [ extract_from_html ] the rule [ cut_from_block ] is applied (that checks for "From" and "Date" ) . But in this case the "Subject" is above from both "From" and "Date" so it passes the check and doesn't get stripped.

This issue appears only when I send from Mailgun to Hotmail.

**Comment by obukhov-sergey** [comment] 2015-09-18 12:28
Actually it's not just Hotmail issue. There are several email clients that use different order of "From: ...", "Date: ..." and "Subject: ..." headers when formatting reply / quotation

**Comment by obukhov-sergey** [comment] 2016-02-19 18:56
I'm going to close it down as a duplicate of https://github.com/mailgun/talon/issues/73

**Closed** 2016-02-19 18:56 UTC
Labels: duplicate
