### ISSUE TITLE
Encoding error in Python 3

### ISSUE THREAD

**Issue by Juanlu001** [mailgun/talon#118] opened 2016-10-27 17:27 UTC
I managed to train my own model with talon, but when trying to use it to extract a signature I got an encoding error:

```
ERROR when extracting signature with classifiers
Traceback (most recent call last):
  File "/home/jlcano/.miniconda3/envs/py3/lib/python3.5/site-packages/talon/signature/extraction.py", line 54, in extract
    markers = _mark_lines(lines, sender)
  File "/home/jlcano/.miniconda3/envs/py3/lib/python3.5/site-packages/talon/signature/extraction.py", line 81, in _mark_lines
    candidate = get_signature_candidate(lines)
  File "/home/jlcano/.miniconda3/envs/py3/lib/python3.5/site-packages/talon/signature/bruteforce.py", line 142, in get_signature_candidate
    markers = _mark_candidate_indexes(lines, candidate)
  File "/home/jlcano/.miniconda3/envs/py3/lib/python3.5/site-packages/talon/signature/bruteforce.py", line 166, in _mark_candidate_indexes
    markers = bytearray('c'*len(candidate))
TypeError: string argument without an encoding
```

**Comment by MinasAbrahamyan** [comment] 2016-11-03 10:30
This is due talon code not ready for Python 3, this error occures with present built-in ML models too

**Comment by obukhov-sergey** [comment] 2016-12-21 06:00
Duplicate of https://github.com/mailgun/talon/issues/42

**Closed by obukhov-sergey** 2016-12-21 06:00 UTC
Labels: duplicate
